### ISSUE TITLE
Artifactory modifies `db.properties` upon launch, leading to puppet and artifactory fighting over the file

### ISSUE THREAD

**Issue by ExalDraen** [autostructure/artifactory#10]
We've just deployed artifactory-pro (5.9.1) using this puppet module and run into the issue described below. 

Do you know of any solutions to this problem? Or better workarounds than what we've got (also described below)?

## Details

When artifactory launches, it reads `db.properties` and, if it finds that the db `password` is not encrypted, modifies that file to encrypt the password. 

For example, 

```conf
password=foobar
```

is turned into something like 
```conf
password=JEW9gKVqXK66PJVWVD...
```

The problem is that the next time puppet runs it identifies that `db.properties` has changed and reverts the change to restore `password` back to its unencrypted form. It also restarts the artifactory service, and the cycle begins again.

## Versions

**Puppet version**: 4.10.8
**`artifactory` module version**: 2.0.13
**artifactory version**: 5.9.1

## Workaround

We've worked around this by not setting any `db_*` parameters in the `artifactory` class, which means puppet does not manage `db.properties`. We have to instead edit this file by hand, which is quite undesirable.

**Comment by alexjfisher** [comment]
I've just updated my artifactory from 5.5 to 5.9 and am now hitting this too. :(

**Comment by alexjfisher** [comment]
@ExalDraen What do you think of my 'fix'?  It's not ideal, but maybe something you can live with.

**Comment by DaveTCode** [comment]
@alexjfisher I worked with @ExalDraen on this and he's now moved on from that role so may not get around to responding to this ticket. Your analysis matches up with where we got to as well, we were mulling over solutions like spotting if the password already existed and not updating it or trying to figure out if it had been encrypted for the same reason. Broadly though they're all crap/magic so I prefer your solution on the basis that at least it's explicit!

Don't know if your company pay for a support contract with artifactory but if you do then it might be worth raising this with them, if they could provide a simple interface to encrypt a password from a CLI then we could get around this.

**Comment by alexjfisher** [comment]
@DaveTCode Turns out my fix is no good.  Looks like there's also a bug in artifactory.  AFAICT the intention is to only encrypt the password if it's not already encrypted, but in reality artifactory decrypts and re-encrypts it every time it starts. See https://github.com/autostructure/artifactory/pull/11#issuecomment-376514890

We've got one instance of artifactory pro, (not pro plus), but I think that means we don't have access to the customer ticket portal.  'Community support forum' is stack overload so I'm not sure how much success I'll have there.

Fortunately, @bryanjbelanger-puppet has a contact, so might be able to get this raised as, like you also figured out, most other 'solutions' I can think of are a bit crappy.  Create a new fact and set 'replace => ! $artifactory_db_password_is_already_encrypted' on the file resource?

**Comment by ExalDraen** [comment]
@alexjfisher I agree with @DaveTCode, yours is the best fix I can think of. Other than that I can  only think of aforementioned bad solutions:

* Give up on managing `db_properties`. Effectively the workaround above, but perhaps more formalized, e.g. behind a check for the artifactory version and with a warning that informs people.
Obviously pretty bad as it means we don't really have infrastructure as code.

* Work out how to spot if a password is encrypted (I think this should be possible from reading the artifactory source, e.g. they seem to start with some common charactes). Bad as passwords will never be able to be updated once set.

The best way forward would be if jfrog could change the way `db_properties` is handled so that it's possible to supply e.g. a SHA256 of a db password (which then won't get touched by artifactory). Or possibly make it possible to disable this (re)encryption behaviour.
Perhaps @bryanjbelanger can raise this as an idea if he's got engagement with jfrog.

**Comment by shaybagants** [comment]
I hope I'm not disturbing this discussion, but I'm wondering what if there was a way to encrypt the db password ahead using a CLI with the existing master key created by Artifactory, or a key that the user provided to Artifactory before the first initialization? this way, the db.properties you have pre-created will already be encrypted and Artifactory will not change it.
Btw, when Artifactory starts at the first time, of there is no master key exists it will indeed create it, but if a valid master key (AES-128) was provided, Artifactory uses it instead of creating new key.

**Comment by frangipanes** [comment]
It looks like artifactory-oss addressed this in v6.6: https://www.jfrog.com/confluence/display/RTF/Configuring+Security#ConfiguringSecurity-HardeningSecurityforSecrets

> To load parameters using this mechanism, place them in the following temporary file before your startup Artifactory: `$ARTIFACTORY_HOME/etc/.secrets/.temp.db.properties`
